version: "3.2"

services:
  database:
    image: dockersecurity/dc17-atsea:atsea_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_DB_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: atsea
    networks:
     - back-tier
    secrets:
      - postgres_password

  appserver:
    image: dockersecurity/dc17-atsea:atsea_app
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
      - payment
    secrets:
      - postgres_password

  payment_gateway:
    image: dockersecurity/dc17-atsea:atsea_payment
    secrets:
      - payment_token
    networks:
      - payment

networks:
  front-tier:
  back-tier:
  payment:

secrets:
  postgres_password:
    file: ./devsecrets/postgres_password
  payment_token:
    file: ./devsecrets/payment_token
